### ISSUE TITLE
Notifications cannot be opened on questions on Codidact Meta and on the Dev Server

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#162]
1. On dev, I can't open the notifications on question pages where I have either a question or an answer
2. On Meta, I can't open the notifications on any questions' pages
3. I can open the notifications on every other community

On the affected pages, this error shows up on loading it (not when clicking the notifications button)
![console](https://cdn.discordapp.com/attachments/676843271762214932/750148684951584849/unknown.png)

The error doesn't show up on unaffected pages.

**Comment by cellio** [comment]
I reproduced this on the dev server:
user: https://dev.codidact.org/users/534
post producing the error: https://dev.codidact.org/questions/68
browser: Firefox (incognito)

Console on page load:

![screen shot of error stack](https://user-images.githubusercontent.com/5557942/91782201-76f65e00-ebca-11ea-881e-03a2cb410435.png)

On that page, the notification indicator appears but clicking on it doesn't produce the modal.  On other pages on the site, I see the notifications just fine.

**Comment by ArtOfCode-** [comment]
Fixed

**Comment by cellio** [comment]
Reported as still happening here: https://meta.codidact.com/questions/279654

An update there says it is specific to posts where you have an answer.  There's an empty this.element where there shouldn't be (?).

**Comment by Istiakshovon** [comment]
Is it still available? I haven't faced it single time after joining Codidact. :thinking:

**Comment by sau226** [comment]
I've tested on dev, and unless I'm missing something, creating an answer on a post, visiting said post and then trying to open up notifications all work perfectly fine. I think we may want to look at closing out this issue and applying a norepro or complete/fixed tag to the meta post

**Comment by trichoplax** [comment]
I agree this looks fixed now. Earlier reports included Firefox users, and I can confirm that I do not see this problem in Firefox. I can visit a question that I asked on Meta, or a question on Meta to which I have posted an answer, and in both cases I can open the notifications panel (ignoring the separate problem that clicking on the icon within the notification button doesn't work - that's [fixed and awaiting release](https://github.com/codidact/qpixel/issues/923)).

If it is decided to close this issue, do we need a status-completed on some or all of these Meta questions:
- https://meta.codidact.com/posts/279654
- https://meta.codidact.com/posts/278275
- https://meta.codidact.com/posts/278171

**Comment by cellio** [comment]
Thanks for testing and reporting back.  Closing and updating those meta posts.
