### ISSUE TITLE
Sorting is broken on user search results page

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#1674]
meta:293726

The Users page shows two sorting buttons, Reputation (default) and Age.  If you use the search, though, then the users matching the search are shown in an unclear order, neither button is "on", and neither button changes the sort order.

At minimum, the buttons should work.  Preferably, we should also initially use whatever sort was active before you did the search.

**Comment by Oaphi** [comment]
I think I've already fixed that in #1633 - judging by the latest commit date, we haven't done any deploys to prod since

**Comment by cellio** [comment]
Oh, thanks for the catch.  It's *almost* fixed; there's one tiny issue remaining, the lack of button highlighting:

<img width="819" height="492" alt="search results in rep order but Reputation button is not lit up" src="https://github.com/user-attachments/assets/f27f1dd9-d3e8-4f4a-b6ae-1442c31d1e4b" />

**Comment by cellio** [comment]
No worries!  You tested all the other configurations; this one was easy to miss. :-)
