### ISSUE TITLE
Answer count on question list includes deleted answers; it shouldn't

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#341]
https://meta.codidact.com/questions/279798

On Code Golf, the "hello world" question (https://codegolf.codidact.com/questions/279147) shows on the question list as having 20 answers.  It actually has 18 visible answers and 2 deleted answers.  A user who cannot see deleted answers reported this mismatch.

I *think* this is a recent regression (last few weeks).

**Comment by ArtOfCode-** [comment]
Fixed. Not sure _when_ it was fixed, or maybe it was a data error, but it's no longer happening.

**Comment by cellio** [comment]
Not fixed:

![question list: 21](https://user-images.githubusercontent.com/5557942/103908962-1ecbed00-50d1-11eb-8228-ddbdef5e86a7.png)

![post: 19](https://user-images.githubusercontent.com/5557942/103908986-27bcbe80-50d1-11eb-9636-46561abe753c.png)

Also:

![profile page: 21](https://user-images.githubusercontent.com/5557942/103909174-60f52e80-50d1-11eb-961b-207cfd2505c5.png)

Or do you mean it won't happen again, as opposed to existing cases being fixed?  Is there any way to find out how many mismatches there are?  I guess the post list isn't reading from the same data as the post itself?

**Comment by ArtOfCode-** [comment]
Oh, _that_ answer count. I thought you were meaning the one that says "19 answers" in your second screenshot.

**Comment by ArtOfCode-** [comment]
Data error; fixed.

**Comment by cellio** [comment]
Recurrence: https://meta.codidact.com/posts/279798  (see update there with reproducer).

I know you said data error before, implying it was a fix to that specific question.  So at minimum we have another question that presumably needs the same fix, but can we figure out what they have in common and see if there are other cases?

**Comment by ArtOfCode-** [comment]
The count appears to be correct at the moment, and testing locally, both creating and deleting answers changes the count as it should. Not saying there's no bug there, but maybe it's somewhere unexpected, or maybe I just can't find it. Have we found any other new repros of this?

**Comment by cellio** [comment]
The "cutting the square" question demonstrates the problem: 

![post list: 1 answer](https://user-images.githubusercontent.com/5557942/108753971-5ec92100-7513-11eb-97f0-72dac7adf209.png)

![post: 0 answers, 1 deleted](https://user-images.githubusercontent.com/5557942/108754007-68eb1f80-7513-11eb-801d-2489e9f06c5f.png)

https://math.codidact.com/posts/278332

**Comment by ArtOfCode-** [comment]
Also fixed for all current cases. Still not clear on why this is happening in the first place, so if you see another one please let me know.

**Comment by cellio** [comment]
Can't reproduce any more and we haven't heard of new cases.  Closing.
