### ISSUE TITLE
Can't log in unless cookies are allowed, results in 500 Internal Server Error

### ISSUE THREAD

**Issue by 1ec2466** [codidact/qpixel#47]
***NOTE: The details are wrong. It's not Javascript, it's site-specific cookies. See the discussion in the comments.***

**Describe the bug**

Trying to log in to a Codidact site results in a 500 error unless Javascript is enabled.

**To Reproduce**

1. Have an account on a Codidact site, such as Writing Codidact.
2. Go to https://writing.codidact.com/ and sign in. Note that signing in works properly.
3. Sign out. Use a plugin such as Noscript or uMatrix to disallow Javascript from writing.codidact.com.
4. Near the top right of the page, click "Sign In"
5. Enter the e-mail address and password associated with the account, leave "Remember me" unchecked, and click "Log in"

**Actual result:**

A text/plain response with the following body:

    500 Internal Server Error
    If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

**Expected behavior**

Returning to the front page of the Codidact site, having been logged in **or** a message is displayed indicating that Javascript is required.

**Screenshots**

Not applicable.

**Desktop (please complete the following information):**

 - OS: Debian GNU/Linux - Buster, up to date
 - Firefox 68.7.0 ESR

**Additional context**

Nothing known relevant; ask if it's needed.

**Comment by ArtOfCode-** [comment]
As far as I know this isn't anything to do with JavaScript, though whether it's allowed or not may have some effect on the response. Try again? There were some data issues that were causing errors which may be what you were seeing, so let's see if fixing those has had any effect.

Also, fair warning: running without JavaScript enabled is not explicitly supported at the moment. It's something we're aiming for, eventually, but you may find things that don't work without it.

**Comment by 1ec2466** [comment]
It looks like I was mistaken; it's not Javascript, it's the specific-site cookie. So the bug report as written is wrong (sorry about that!) but the error is still very much unhelpful.

**Comment by ArtOfCode-** [comment]
Login should set a `_qpixel_session` cookie for the site domain (`writing.codidact.com`, not `codidact.com`) AFAIK. Probably one to look into and see if we can move it to the second-level domain eventually, but that's not critical. Does login work for you now, or is it still erroring?

**Comment by 1ec2466** [comment]
Yes, logging in seems to work fine when cookies are allowed for (in this case) `writing.codidact.com`. The error message still appears to be displayed when those cookies are disabled. I understand that *logging in* doesn't work with cookies disabled, but a more descriptive error message might be nice.

**Comment by ArtOfCode-** [comment]
Fixed by 084f269

**Comment by 1ec2466** [comment]
I'm still getting what looks like the same error with version `15f3ef8c` 2020-05-01 23:14:31 +0100.

**Comment by luap42** [comment]
@1ec2466 Have you got an error ID? They should be shown on the error page (added recently).

**Comment by 1ec2466** [comment]
Sorry, I'm still getting the same plain-text "500 Internal Server Error" message as in the initial issue. I can however give you a timestamp: 2020-05-04T12:21:10Z, +/- maybe a few seconds. Hopefully that'll point you in the right direction in the server logs.

When I additionally allowed cookies in uMatrix for the specific FQDN and reloaded the page that failed (and in doing so reposted the request) I was signed in properly with no apparent error.

**Comment by ArtOfCode-** [comment]
Is this still with JS disabled, @1ec2466?

**Comment by 1ec2466** [comment]
@ArtOfCode-  No, Javascript was a misdiagnosis on my part. I get the error with first-party cookies disabled, but with first-party cookies enabled, I get signed in without a problem.

**Comment by ArtOfCode-** [comment]
@1ec2466 Aye, that's expected. I'm asking about JavaScript because I've added detection of whether cookies are enabled or not to login, and login is disabled if they're not available. That's in JS, though, so if you're still looking at it with JS disabled, you'll get this error.

**Comment by 1ec2466** [comment]
@ArtOfCode- I just did a bit more testing. With version 699c8f1e (2020-05-08 21:20:27 +0100), with Javascript enabled and cookies disabled, I don't see any notification on the sign in page that signing in won't work, but at least I don't get any error when I try (though I don't get signed in either; which is expected behavior). When at that point I enable cookies in uMatrix and reload the front page, I remain signed out, so it looks like the cookie was never set at all. When I keep cookies enabled and sign in again, I get signed in normally. So perhaps not perfect, but definitely a lot better than an Internal Server Error, so I'm happy now.
